version: '3.1'

services:
  db: 
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: nest
    ports:
      - "3306:3306"
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./app:/usr/app
    ports:
      - "3000:8081"
    depends_on:
      - db
    networks:
      - default

networks:
  default:
