version: '3.1'

services:
  db: 
    env_file:
      - ./app/.env
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    networks:
      - default

  app:
    env_file:
      - ./app/.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./app:/usr/app
    ports:
      - "3000:8081"
    depends_on:
      - db
    networks:
      - default
  
  redis:
    env_file:
      - ./app/.env
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
